# site settings

title: Apex Mission Systems LLC
description: Joint Venture between Peterson Technologies and iNovex.
taglong: Joint Venture between Peterson Technologies and iNovex.
tagshort: Joint Venture (JV)
url: https://apexmissionsystems.com
baseurl: "/"
permalink: pretty
repo: https://github.com/PetersonTechnologies/apex-website

# author settings

author:
  name: Apex Mission Systems LLC
  email: info@apexmissionsystems.com
photo: /assets/jpg/logo.jpeg

# social media links

social:
  facebook: PetersonTechnologies
  github: PetersonTechnologies
  linkedin: peterson-technologies

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
